### ISSUE TITLE
<Towntag.balance> seems to be broken

### ISSUE THREAD

**Issue by realdagumboss** [DenizenScript/Depenizen#310] opened 2020-02-13 06:17 UTC
https://one.denizenscript.com/paste/65222

Not sure what the issue is but it doesn't want to work.

**Comment by mcmonkey4eva** [comment] 2020-02-13 06:44
The problem is you updated to the a Towny version released within the last 15 days... because 15 days ago they changed the relevant API calls in use internally.
Depenizen will need to be updated to target the new Towny API.

**Closed** 2020-02-13 08:28 UTC
Labels: Will Do, bug
