### ISSUE TITLE
MythicMobs Mechanic

### ISSUE THREAD

**Issue by quochungudon** [DenizenScript/Depenizen#308] opened 2020-02-06 11:24 UTC
Can you add more mechanics for mythicmobs ? Like mob score , mob level , mob threat 

Here is some link:
https://www.mythicmobs.net/manual/doku.php/databases/mobs/levels
https://www.mythicmobs.net/manual/doku.php/databases/mobs/modules/threattables

**Comment by mcmonkey4eva** [comment] 2020-02-07 12:01
Looks to be a duplicate of #260

**Closed by mcmonkey4eva** 2020-02-07 12:01 UTC
