### ISSUE TITLE
Redprotect Support

### ISSUE THREAD

**Issue by Aldiwildan77** [DenizenScript/Depenizen#361] opened 2021-04-10 16:23 UTC
It would be nice to implement a Redprotect API so we can use it using denizen.

Example Redprotect Link:
- [getRegion](https://github.com/FabioZumbi12/RedProtect/blob/eed3c333de8280e8246d22661225c23de1c30a6e/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/API/RedProtectAPI.java#L86)
- [getPlayerRegions](https://github.com/FabioZumbi12/RedProtect/blob/eed3c333de8280e8246d22661225c23de1c30a6e/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/API/RedProtectAPI.java#L122)

Example custom tag 
- [RegionTag](https://github.com/FabioZumbi12/RedProtect/blob/eed3c333de8280e8246d22661225c23de1c30a6e/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/Region.java#L47), for region class to store multiple action/data of region such as:
```
1. name
2. location
3. leader
4. admin
5. member
```

Example usage of tag using denizen (maybe if possible):
- ``<RegionTag.name>`` return ElementTag for region name
- ``<RegionTag.location>`` return ElementTag for location of region
- ``<rp[<LocationTag>]>`` return RegionTag based on location tag
- ``<rp[<LocationTag>].name>`` return ElementTag for region name
- ``<rp[<LocationTag>].leader>`` return ListTag (PlayerTag) of leaders in current region 
- ``<rp[<PlayerTag>]>`` return ListTag (RegionTag) of player's region based on player tag
- ``<rp[<PlayerTag>].get[0].name>`` return ElementTag for region name
- ``<rp[<PlayerTag>].get[0].location>`` return LocationTag of the first index in ListTag (RegionTag)

**Comment by mcmonkey4eva** [comment] 2021-04-10 16:23
Duplicate of #244

**Closed by mcmonkey4eva** 2021-04-10 16:23 UTC

**Comment by Aldiwildan77** [comment] 2021-04-10 16:53
so when does the Redprotect Support (#244) will be launched? @mcmonkey4eva

**Comment by mcmonkey4eva** [comment] 2021-04-10 16:54
I think you're confused about how GitHub works. #244 is somebody else's request for the same thing. You should add to that post, not open your own.

Also, if you're not already on the Discord, join @ https://discord.gg/Q6pZGSR
